source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DTScalePicker_Example', :exclusive => true do
  pod "DTScalePicker", :path => "../"
end

target 'DTScalePicker_Tests', :exclusive => true do
  pod "DTScalePicker", :path => "../"

  
end
